### ISSUE TITLE
Adjustments for 750 Boost

### ISSUE THREAD

**Issue by evancameron** [Net-Geek/ShoeBot#2]
What adjustments need to be made to accommodate for the 750 Boost release this Saturday?

Right now I get a lengthy error in chrome when the extension runs, even for a product that is currently for sale.

**Comment by Net-Geek** [comment]
Looks like adidas changed their endpoints. Feel free to inspect the network traffic upon selecting a shoe on adidas, and change the endpoint in the code. I won't have time before the release to do so.
